# Generated by Django 3.2.11 on 2022-01-16 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desafiotech', '0002_auto_20220116_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruit',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='desafiotech.region'),
        ),
    ]
