# Generated by Django 3.2.11 on 2022-01-16 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desafiotech', '0003_fruit_region'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fruit',
            old_name='region',
            new_name='nameRegion',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='name',
            new_name='nameRegion',
        ),
    ]
