# Generated by Django 3.2.11 on 2022-01-16 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desafiotech', '0004_auto_20220116_2053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fruit',
            old_name='nameFruit',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='fruit',
            old_name='nameRegion',
            new_name='region',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='nameRegion',
            new_name='name',
        ),
    ]
